import os
from typing import Optional

import resend
from dotenv import load_dotenv

load_dotenv()

resend.api_key = os.getenv("RESEND_API_KEY")


def send_email(
    to: str | list[str],
    subject: str,
    html: Optional[str] = None,
    text: Optional[str] = None,
    from_email: Optional[str] = None,
    reply_to: Optional[str] = None,
) -> dict:
    """
    Send an email using Resend.

    Args:
        to: Recipient email address or list of addresses
        subject: Email subject line
        html: HTML content of the email (optional if text provided)
        text: Plain text content of the email (optional if html provided)
        from_email: Sender email address (defaults to RESEND_FROM_EMAIL env var)
        reply_to: Reply-to email address (optional)

    Returns:
        dict with 'id' of the sent email

    Raises:
        ValueError: If neither html nor text content is provided
        resend.exceptions.ResendError: If email sending fails
    """
    if not html and not text:
        raise ValueError("Either 'html' or 'text' content must be provided")

    sender = from_email or os.getenv(
        "RESEND_FROM_EMAIL", "onboarding@resend.dev")

    params: resend.Emails.SendParams = {
        "from": sender,
        "to": [to] if isinstance(to, str) else to,
        "subject": subject,
    }

    if html:
        params["html"] = html
    if text:
        params["text"] = text
    if reply_to:
        params["reply_to"] = reply_to

    return resend.Emails.send(params)


def send_weekly_email(
    to: str,
    review_content: str,
    week_label: str = "This Week",
) -> dict:
    """
    Send a weekly review email with formatted HTML.

    Args:
        to: Recipient email address
        review_content: The weekly review content (markdown or plain text)
        week_label: Label for the week (e.g., "Week of Jan 6")

    Returns:
        dict with 'id' of the sent email
    """
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 600px;
                margin: 0 auto;
                padding: 20px;
            }}
            h1 {{
                color: #2563eb;
                border-bottom: 2px solid #e5e7eb;
                padding-bottom: 10px;
            }}
            .content {{
                background: #f9fafb;
                padding: 20px;
                border-radius: 8px;
                white-space: pre-wrap;
            }}
            .footer {{
                margin-top: 30px;
                padding-top: 20px;
                border-top: 1px solid #e5e7eb;
                font-size: 12px;
                color: #6b7280;
            }}
        </style>
    </head>
    <body>
        <h1>📊 Weekly Review: {week_label}</h1>
        <div class="content">{review_content}</div>
        <div class="footer">
            Generated by Obsidian Agent ✨
        </div>
    </body>
    </html>
    """

    return send_email(
        to=to,
        subject=f"📊 Your Weekly Review - {week_label}",
        html=html_content,
        text=review_content,
    )


if __name__ == "__main__":
    # Test sending an email
    result = send_email(
        to="delivered@resend.dev",
        subject="Test Email from Obsidian Agent",
        html="<h1>Hello!</h1><p>This is a test email.</p>",
        text="Hello! This is a test email.",
    )
    print(f"Email sent! ID: {result['id']}")
